apiVersion: v1
kind: Pod
metadata:
  name: schdule-pod-require-podaffinity-demo1
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1

---

apiVersion: v1
kind: Pod
metadata:
  name: schdule-pod-require-podaffinity-demo2
  labels:
    app: backend
    tier: db
spec:
  containers:
  - name: busybox
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "sleep 3600"]
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values: 
            - myapp
        topologyKey: kubernetes.io/hostname # 其实就是节点的标签名称
