apiVersion: v1
kind: Pod
metadata:
  name: schdule-pod-nodeaffinity-demo-2
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
  affinity:
    nodeAffinity:
      # 不强制要求，如果没有也会寻找一个合适node创建pod  
      preferredDuringSchedulingIgnoredDuringExecution:  
      - preference:
          matchExpressions:
          - key: zone
            operator: In
            values:
            - foo
            - bar
        weight: 60

