apiVersion: apps/v1
kind: Deployment
metadata: 
  name: taint-deploy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      release: canary
  template:
    metadata: 
      labels:
        app: myapp
        release: canary
    spec: 
      containers:
        - name: myapp
          image: ikubernetes/myapp:v2
          ports:
            - name: http
              containerPort: 80  
      tolerations: 
      - key: "node-type"
        #operator: "Equal"
        #value: "production"
        operator: "Exists"
        value: ""
        effect: "NoSchedule"