apiVersion: v1
kind: Pod
metadata: 
  name: readiness-httpget-pod
  namespace: default
spec:
  containers:
    - name: readiness-httpget-container
      image: ikubernetes/myapp:v1
      imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 80
      readinessProbe: # 就绪探测，是否ready
        httpGet:
          port: http
          path: /index.html
        initialDelaySeconds: 1 # 启动后1s执行
        periodSeconds: 3 # 间隔时间为3s探测一次
  # restartPolicy:         